### ISSUE TITLE
Lab1: Comments

### ISSUE THREAD

**Issue by ringavirda** [Maks9m/Labs#2]
Most of the task is completed but there was second part to the type counting thing. 

Also, please, don't upload code with typos, especially in file names.

**Comment by Maks9m** [comment]
Thank you, I have added dynamic variant of exercises 3 and fixed typos. Could you look through again? And will this fix my mark?

**Comment by Maks9m** [comment]
> Most of the task is completed but there was second part to the type counting thing.
> 
> Also, please, don't upload code with typos, especially in file names.

Thank you, I have added dynamic variant of exercises 3 and fixed typos. Could you look through again? And will this fix my mark?

**Comment by ringavirda** [comment]
Fine, but don't forget about code style, indentation and stuff. Or at least use <alt> + <shift> + f combo to autoformat file, if you are on vs code.
